### ISSUE TITLE
What crystal is used in this project

### ISSUE THREAD

**Issue by GitOeli** [srwalter/cbus-emulator#1]
I want to build this project, but i cant find information on U3. What frequency does it need to be?

**Comment by srwalter** [comment]
The design should not be particularly sensitive to the clock speed.  The head unit is the master of the bus and drives the clock, so the PIC just has to be fast enough to detect the edges on that clock and react.

It appears that I configured the simulator (gpsim) to run at 20MHz, so that's probably the safest bet.
